Repository avplayer/ucoro, pull requests merged in 2024-10, with the labels that each got.

#25 update clang-format and code style
  .clang-format
  include/ucoro/awaitable.hpp
Labels: code style

#24 初步添加xmake支持
  .gitignore
  tests/xmake.lua
  xmake.lua
Labels: enhancement, help wanted

#26 支持等待 .detach() 创建的协程
  include/ucoro/awaitable.hpp
  tests/CMakeLists.txt
  tests/test2/CMakeLists.txt
  tests/test2/test2.cpp
Labels: enhancement

#27 callback_awaitable 自适应executor模式
  include/ucoro/awaitable.hpp
  tests/test5/test.cpp
  tests/test_asio/test_asio.cpp
  tests/test_executor/test_executor.cpp
  tests/testlibuv/test.cpp
  tests/testqt/testqt.cpp
Labels: enhancement

#40 删除 awaitable_detached<> 类。减少代码重复
  include/ucoro/awaitable.hpp
  tests/test3/test.cpp
Labels: bug, enhancement
